version: 1

formatters:
  json:
    format: '{"timestamp": "%(asctime)s", "level":"%(levelname)s", "message":"%(message)s","name":"%(name)s"}'

handlers:
  console:
    class: logging.StreamHandler
    formatter: json
    level: INFO
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    formatter: json
    level: INFO
    filename: logs/etl.json
    maxBytes: 10485760
    backupCount: 5
    encoding: utf8

root: 
  level: INFO
  handlers: [console,file]
