run:
  batch_size: 100
  max_retries: 3
  backoff_seconds: 5
  target_table1: public.customers
  target_table2: public.loans
  target_table3: public.transactions
  target_table4: public.accounts

sources:
  api:
    endpoint_accounts: "accounts"
    endpoint_customers: "customers"
    endpoint_branches: "branches"
    endpoint_txn: "transactions"
    endpoint_loan: "loans"
    page_param: "page"
    per_page_param: "per_page"
    per_page: 6
    data_key: "data"
  load:
    mode: "upsert"

